- name: Configure Ubuntu EC2 Instance
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - htop
          - curl
          - unzip
          - awscli
        state: present

    - name: Enable firewall and allow SSH
      ufw:
        state: enabled
        policy: deny
        rule: allow
        port: 22
        proto: tcp

    - name: Install CloudWatch Agent
      shell: |
        curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        sudo dpkg -i -E ./amazon-cloudwatch-agent.deb
        
    - name: Enable and start CloudWatch Agent
      systemd:
        name: amazon-cloudwatch-agent
        enabled: yes
        state: started
