name: Upload Lambda ZIP to S3

on:
  push:
    paths:
      - 'lambda_functions/**'
      - '.github/workflows/lambda_upload.yml'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install zip
        run: sudo apt install zip

      - name: Zip Lambda Functions
        run: |
          mkdir -p lambda_zips
          for file in lambda_functions/*.py; do
            name=$(basename $file .py)
            cp "$file" "./${name}.py"
            zip "lambda_zips/${name}.zip" "${name}.py"
            rm "${name}.py"
          done
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          for zipfile in lambda_zips/*.zip; do
            aws s3 cp "$zipfile" s3://${{ secrets.LAMBDA_BUCKET_NAME }}/$(basename "$zipfile")
          done
      
      - name: Update Lambda Functions
        shell: bash
        run: |
          declare -A function_map=(
            ["restart_ec2_lambda"]="RestartEC2Lambda"
            ["revoke_s3_access_lambda"]="RevokeS3AccessLambda"
            ["revoke_ssh_lambda"]="RevokeSSHAccessLambda"
            ["recover_ec2_lambda"]="RecoverEC2InstanceLambda"
            ["increase_memory_lambda"]="IncreaseMemoryLambda"
            ["memory_test_lambda"]="MemoryTestLambda"
          )
        
          for zipfile in lambda_zips/*.zip; do
            filename=$(basename "$zipfile" .zip)
            lambda_name=${function_map[$filename]}
        
            if [ -z "$lambda_name" ]; then
              echo "No Lambda mapping found for $filename. Skipping..."
              continue
            fi
        
            echo "Updating $lambda_name from $zipfile..."
        
            aws lambda update-function-code \
              --function-name "$lambda_name" \
              --s3-bucket "${{ secrets.LAMBDA_BUCKET_NAME }}" \
              --s3-key "$(basename "$zipfile")" \
              --publish
          done
        