name: Terraform Apply

on:
  push:
    paths:
      - 'monitored_environment/**'
      - 'use_cases/**'
      - '.github/workflows/terraform_deploy.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Write tfvars file
        run: echo "${{ secrets.TF_VARS }}" > terraform.tfvars

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          lambda-bucket-name: ${{ secrets.LAMBDA_BUCKET_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve
